/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaworkflowservice;

import static javaworkflowservice.createcomponent.InitiateComponentCreation.excecuteCreateCompWorkflow;
import static spark.Spark.*;

public class App {

    public static void main(String[] args) {
        port(9099); // run the service on port 9099.
        path("/workflow", () -> {
            get("/component/:componentName", (req,res)->{
                String componentName = req.params(":componentName");
                System.out.println("workflow service: exucuting workflow for " + componentName);
                excecuteCreateCompWorkflow(componentName);
                return "Component Creation initiated, name: "+ req.params(":componentName");
            });
        });
    }
}
